<a href="https://colab.research.google.com/github/vasasunilkumar/ML-lab/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


diff b/w list and numpy array
lsit can store different type of data that is [int,float,string].
arrray can store same daya type of data that is [1,2,3,4]

In [63]:
a = np.array([[3,6,9,12],[15,18,21,24]],dtype="int")
a/3


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [64]:
list1 = [2,4,6,8]
list1/2

TypeError: ignored

In [0]:
a=np.arange((10),dtype="int")
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array below ex

In [0]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

two dimensional array using tuple

In [0]:
a = np.array(((1,2),(2,3)))
a

array([[1, 2],
       [2, 3]])

in below example mention the type of data that is int,float,complex....

In [0]:
a=np.array([2,3],dtype="complex")
print(a)

[2.+0.j 3.+0.j]


in below example mention ndmin that is ndimensinoal array below exmple output is two dimensional array i mention the ndmin=2 i.e two dimensional... array

In [0]:
a=np.array([1,2,3,4],ndmin=2,dtype="complex")
print(a)


[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]]


In [0]:
a = np.array([[1,2,3],[4,5,6],[4,8,9]])
a.shape

(3, 3)

In [68]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],order="c")
a.shape=(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
a=np.arange(24)
b=a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

arange() creates an array of evenly spaced values...

In [72]:
a = np.arange(1,10,2 )
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(20,dtype="complex")
a

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [5]:
a = np.array(((1,2),(2,2)))
a

array([[1, 2],
       [2, 2]])

zero() creates array filled with 0s

In [7]:
np.zeros((3,4),dtype="int")


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

ones() creates array filled with ones..

In [10]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

linspace() creates array filled evenly spaced values....


In [20]:
a = np.linspace(5,100,num=5,dtype="int",endpoint="false")
a

array([  5,  28,  52,  76, 100])

In [26]:
a = np.linspace(1,1000,dtype="int",num=50)
a

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

Linspace()  if not mention the num parameter in linspace consider has default num in the example below..

In [31]:
a = np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

eye() return ndarray(n,m) here n is for rows and m is for coloumns
identity()  it is similar to eye()function. The identity array is a sqare array.

In [39]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [42]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

random()
rand() uniformly distributed values

In [52]:
np.random.rand(5,2)

array([[0.7818003 , 0.83091281],
       [0.07794206, 0.38683082],
       [0.17813502, 0.94490919],
       [0.09919887, 0.31367923],
       [0.39300498, 0.99832797]])

randn() normaly distributed values

In [51]:
np.random.randn(5,4)

array([[-1.10266163, -0.41510875,  1.10816509, -0.4033804 ],
       [ 0.60734571, -0.44360219,  1.70325896,  0.07057581],
       [-0.14614659,  0.87095892, -0.00448117, -0.97264192],
       [-0.99680317, -0.39771168,  1.25991018,  0.06020896],
       [-1.0821774 , -0.06698528, -0.14708126,  1.03966192]])

randint() uniformly distributed integers in a given range

In [54]:
np.random.randint(10,size=5)

array([6, 6, 8, 6, 9])

In [56]:
np.random.randint(2,5,size=(2,5))

array([[3, 3, 3, 4, 4],
       [4, 3, 2, 2, 2]])

randf() uniformly distributed floating point

In [58]:
np.random.ranf(5)

array([0.91092291, 0.77360558, 0.04445007, 0.38628827, 0.98489474])