<a href="https://colab.research.google.com/github/vasasunilkumar/ML-lab/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [0]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

In [0]:
a = np.array(((1,2),(2,3)))
a

array([[1, 2],
       [2, 3]])

In [0]:
a=np.array([2,3],dtype="complex")
print(a)

[2.+0.j 3.+0.j]


In [0]:
a=np.array([1,2,3,4],ndmin=2,dtype="complex")
print(a)


[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]]


In [23]:
a = np.array([[1,2,3],[4,5,6],[4,8,9]])
a.shape

(3, 3)

In [38]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],order="c")
a.shape=(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a=np.arange(24)
b=a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])